### PR TITLE
Created LICENSE

### PR DESCRIPTION
**Pull request by wlk**
The project was missing a license information, I have created a license file with Apache License (the safe and reasonable default)

### CODE REVIEW

**Comment by litch** [comment]
FWIW, we favor MIT in our open-source projects: (https://github.com/obsidian-btc/event-store-client-http)

**Comment by litch** [comment]
Thank you for thinking to do this, btw.

**Comment by wlk** [comment]
ok, let me update PR to MIT license

**Comment by wlk** [comment]
done

**Pull request merged**
